spring:
  application:
    name: clustering-user-service
server:
  port: 7211

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 10
    metadata-map:
      instance-id: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}

management:
  endpoint:
    restart:
      enabled: true